# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'testapp' do

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for testapp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'testappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end